### ISSUE TITLE
Merge back to TextAnalysis

### ISSUE THREAD

**Issue by aviks** [zgornel/StringAnalysis.jl#2]
Is there no way we can merge this work back to TextAnalysis? I'm happy to make API changes to TextAnalysis and give you rights to commit

**Comment by zgornel** [comment]
Hi @aviks,
Thank you for inquiring.
Perhaps it would be best to go a bit into why I forked the package in the first pace, it may help explain my decisions better: first, the presence of features that I consider somewhat unnecessary and unreliable (i.e. sentiment analysis model, [this](https://github.com/JuliaText/TextAnalysis.jl/pull/106)) second, the slow pace of pull requests feedback and third, the massive number of dependencies (direct as well as indirect). Since in my case TextAnalysis was a critical dependency and my specific requirements more limited in scope, the circumstances forced me to fork it and take it through a quite large re-factoring operation to better suit the downstream applications I develop.
I have to be honest here, participating in developing TextAnalysis would be too much for me. I'm doing this work on my own time and budget and efficiency in development is important. Plus, the rate of change may not suit all users. I'd be happy to help out with back-porting features back into TextAnalysis though.
Best,
Corneliu
